{
  dataset_parameters : {
    database_folder: 'database',
    start_year: 2024,
    end_year: 2025,
    cml_file: '',
    train_size: 0.7,
    test_size: 0.1,      #test set size
    seed: 111,           #seed for randomness in training/test split
    geography_bounds: {
      left: 103.6,
      right: 104.1,
      top: 1.5,
      bottom: 1.188
    },
    cml_folder: 'combined_microwave_link_data_2024_2025.nc',
    include_lpe: True,
  },

  visualisation: {
    bounds: [0.1, 0.2, 0.5, 1, 2, 4, 7, 10, 20]
  },

  country_info: {
    name: 'Singapore',
    country_bounds: {"left": 103.6, "right": 104.1, "top": 1.5, "bottom": 1.188}
  },

  filters: {
      uptime_threshold: 0.9
  },

  training_params: {
      fold_count: 2,
      seed: 123,
      batch_size: 256, #hyper_param
      epochs: 100,
      early_stop: 5,
  },

  datasources: ['raingauge', 'radar', 'cml'],

  layer_connect: {
    gauge_gauge: 5, #hyper_param
    radar_gauge: 9, #hyper_param
    cml_gauge: 5, #hyper_param
    is_directed: False
  },

  model: {
    hidden_channels: 32, #hyper_param
    num_layers: 2, #hyper_param
    learning_rate: 0.001,
    weight_decay: 1e-4,
  }
}
